### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#26]
- [x] /datasets - list all datasets #1 
- [x] /datasets/some-dataset - show a dataset #4 
- [ ] /organizations - list all organizations #5 
- [ ] /organizations/some-org - show an organization
- [ ] /groups - list all groups #6 
- [ ] /groups/some-group - show a group

**Comment by rodowi** [comment]
do it https://docs.angularjs.org/api/ngRoute/service/$route
